name: 'Compile Elisp Package'
description: 'Compile Elisp packages with byte compilation'
author: 'Commercial Emacs'

branding:
  icon: 'zap'
  color: 'purple'

inputs:
  package-dir:
    description: 'Directory containing .el files to compile'
    required: false
    default: '.'
  compile-all:
    description: 'Compile all .el files in directory recursively'
    required: false
    default: 'false'
  load-path:
    description: 'Additional directories to add to load-path (colon-separated)'
    required: false

outputs:
  elc-files:
    description: 'Number of byte compiled files generated'

runs:
  using: 'node20'
  main: 'dist/index.js'
